# Generated by Django 3.1.4 on 2020-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_sys', '0002_auto_20201218_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
