# Generated by Django 3.1.4 on 2020-12-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tag', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_tags',
            field=models.ManyToManyField(blank=True, to='my_tag.Tag'),
        ),
    ]
